// <auto-generated />
namespace IssueTracker_web_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LoadRoles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoadRoles));
        
        string IMigrationMetadata.Id
        {
            get { return "202112152114104_LoadRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
