// <auto-generated />
namespace IssueTracker_web_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tickets));
        
        string IMigrationMetadata.Id
        {
            get { return "202111302111570_Tickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
